{% set name = "historydag" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc02f7d4a92ffda70e76968891ad509faa804b461dd84b3d9d14e1c58ad252a8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six
    - pyqt
    - ete3
    - biopython
    - python-graphviz

test:
  imports:
    - historydag
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://matsengrp.github.io/historydag
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A basic history DAG implementation
  description: |
    Historydag is a basic history DAG implementation for Python 3.7+
    written in pure Python. A history DAG object compactly expresses
    a collection of internally labeled trees.
  doc_url: https://matsengrp.github.io/historydag
  dev_url: https://github.com/matsengrp/historydag

extra:
  recipe-maintainers:
    - willdumm
